"""Trademark knockout search agent package.

This package contains deterministic v1 helpers for trademark knockout
screening, plus a minimal LangGraph Studio entry point.
"""

from src.tm_knockout_search_agent.deep_agent import (
    TMKnockoutAgentConfig,
    TMKnockoutSearchAgent,
    TM_KNOCKOUT_AGENT_NAME,
    check_tm_knockout,
    create_knockout_search_agent,
    create_tm_knockout_search_agent,
)
from src.tm_knockout_search_agent.eval_runner import (
    MockEvalRunResult,
    MockEvalStatus,
    run_tm_knockout_mock_e2e,
)
from src.tm_knockout_search_agent.state import (
    AgentState,
    CandidateReference,
    ClaimBreakdown,
    ClaimElement,
    ElementMapping,
    EvidenceSnippet,
    FinalDecision,
    KnockoutAssessment,
    KnockoutSearchRequest,
    QueryGroup,
    SearchBudget,
    SearchPlan,
    SearchScope,
    SessionManifest,
    TMKnockoutState,
    TrademarkCandidate,
    TrademarkCandidateSource,
    TrademarkFallbackStrategy,
    TrademarkQueryGroup,
    TrademarkQueryIntent,
    TrademarkSearchBudget,
    TrademarkSearchCriteria,
    TrademarkSearchPlan,
    TrademarkSearchSource,
    TrademarkSearchStage,
    WorkflowStage,
)

__all__ = [
    "TM_KNOCKOUT_AGENT_NAME",
    "TMKnockoutAgentConfig",
    "TMKnockoutSearchAgent",
    "check_tm_knockout",
    "create_knockout_search_agent",
    "create_tm_knockout_search_agent",
    "MockEvalRunResult",
    "MockEvalStatus",
    "run_tm_knockout_mock_e2e",
    "CandidateReference",
    "ClaimBreakdown",
    "ClaimElement",
    "ElementMapping",
    "EvidenceSnippet",
    "FinalDecision",
    "KnockoutAssessment",
    "KnockoutSearchRequest",
    "QueryGroup",
    "SearchBudget",
    "SearchPlan",
    "SearchScope",
    "SessionManifest",
    "TMKnockoutState",
    "TrademarkCandidate",
    "TrademarkCandidateSource",
    "TrademarkFallbackStrategy",
    "TrademarkQueryGroup",
    "TrademarkQueryIntent",
    "TrademarkSearchBudget",
    "TrademarkSearchCriteria",
    "TrademarkSearchPlan",
    "TrademarkSearchSource",
    "TrademarkSearchStage",
    "WorkflowStage",
    "AgentState",
]
