variable "account_id" {
  type        = string
  description = "Account ID generated in build_setting.yml"
}

variable "account_name" {
  type        = string
  description = "Account name given in project_setting.yml"
}

variable "acm_certificate_arn" {
  type        = string
  description = "ARN for wildcard certificate for this domain"
}

variable "app_family" {
  type        = string
  description = "Application family given in project_setting.yml"
}

variable "app_name" {
  type        = string
  description = "Application name given in project_setting.yml"
}

variable "app_version" {
  type        = string
  description = "Application version generated by Jenkins build"
}

variable "bastion_sg_name" {
  type        = string
  description = "Bastion Security-Group name generated in build_setting.yml"
}

variable "config_project_key" {
  type        = string
  description = "(required) Bitbucket project key used to find deployment-automation repo for configuration."
}

variable "env_name" {
  type        = string
  description = "Environment name given in project_setting.yml"
}

variable "env_private_dns" {
  type        = string
  description = "Private DNS name generated in build_setting.yml"
}

variable "env_private_hosted_zone" {
  type        = string
  description = "Private DNS hosted zone id generated in build_setting.yml"
}

variable "env_public_dns" {
  type        = string
  description = "Public DNS name generated in build_setting.yml"
}

variable "env_public_hosted_zone" {
  type        = string
  description = "Public DNS hosted zone id generated in build_setting.yml"
}

variable "main_region" {
  type        = string
  description = "Main region name given in project_setting.yml"
}

variable "nat_gw_ips" {
  type        = string
  description = "NAT Gateway IPs generated in build_setting.yml"
}

variable "owner_email" {
  type        = string
  description = "Email address of the application owner given in project_setting.yml"
}

variable "private_subnets" {
  type        = string
  description = "Private subnets generated in build_setting.yml"
}

variable "region" {
  type        = string
  description = "Region name given in project_setting.yml"
}

variable "ssh_key" {
  type        = string
  description = "SSH key name generated in build_setting.yml"
}

variable "vpc_id" {
  type        = string
  description = "VPC ID generated in build_setting.yml"
}

variable "vpc_cidr" {
  type        = string
  description = "VPC CIDR generated in build_setting.yml"
}

variable "aws_profile" {
  type        = string
  description = "AWS profile generated from build_setting.yml"
}

variable "git_revision" {
  type        = string
  description = "Git revision from Jenkins Pipeline environment variables"
}

variable "git_repo" {
  type        = string
  description = "Git repo from Jenkins Pipeline environment variables"
}

# ECS Attributes
variable "listener_port" {
  type = number
}
variable "service_path" {
  type = string
}
variable "healthcheck_port" {
  type = number
}
variable "healthcheck_path" {
  type = string
}
variable "task_cpu" {
  type = number
}
variable "task_mem" {
  type = number
}
variable "ecs_launchtype" {
  type = string
}
variable "ecs_platform_version" {
  type = string
}
variable "ecs_autoscaling_desired" {
  type = string
}
variable "ecs_autoscaling_minmax" {
  type = string
}
variable "ecs_autoscaling_target_metric" {
  type = string
}
variable "ecs_autoscaling_target_value" {
  type = string
}
variable "ecs_deploy_wait_for_steady_state" {
  type = bool
}
variable "ecs_bastion_ingress_ports" {}

# ECS Scheduled Scaling

variable "alb_consumer_cidrs" {
    type        = list(any)
    description = "List of CIDRs for ALB access"
}

variable "metrics_enabled" {}

# Fixed values
variable "all" {
    description = "Used in SG rules"
    type        = string
    default     = -1
}

# Fixed values
variable "tags" {
  type = map(string)
}

locals {
  # short_app_name is used for ALB naming, if var.app_name is too long it may be necessary to shorten this value
  short_app_name     = var.app_name
  long_service_name  = "${var.app_name}-${var.env_name}-${var.region}"
  service_name       = "${var.app_name}-${var.env_name}"
  short_service_name = var.app_name
  major_env          = split("-", var.env_name)[0]
  # Used to split env names (e.g. dev-snapshot) using hyphen as denominator
  # Terraform lacks a less idiotic way to determine whether a string contains a particular character...
  minor_env = replace(var.env_name, "-", "") != var.env_name ? split("-", var.env_name)[1] : var.env_name

  common_tags = {
    "Name"                = "${var.app_family}-${var.app_name}-${var.env_name}"
    "Layer"               = "IPDS_PISA"
    "Product"             = "Derwent Patent Analytics"
    "Environment"         = "${var.env_name}-dpa"
    "Owner"               = var.owner_email
    "TerraformRepo"       = var.git_repo
    "TerraformPath"       = "deploy/terraform/continuous"
    "tr:appName"          = var.app_name
    "tr:appFamily"        = var.app_family
    "tr:environment-type" = var.env_name
  }
}
